# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinformationchatentry',
            name='target',
            field=models.CharField(default='sens', max_length=200),
            preserve_default=False,
        ),
    ]
