# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0002_requestinformationchatentry_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lang',
            field=models.CharField(default='fi', max_length=10),
        ),
    ]
