# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0003_request_lang'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='request',
            managers=[
            ],
        ),
    ]
