# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0004_auto_20181101_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHandlerChatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('target', models.CharField(max_length=200)),
            ],
            managers=[
                ('requestHandlerChat', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requesthandlerchatentry',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request'),
        ),
    ]
