# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0005_auto_20181110_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestChatEntry',
            new_name='RequestSensitiveChatEntry',
        ),
    ]
