# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0006_auto_20181110_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogentry',
            name='action',
            field=models.CharField(choices=[('VIEW', 'views request'), ('ACC', 'accepts terms of use'), ('POS', 'accepts use of data'), ('RESET', 'resets the decision for a new round'), ('NEG', 'declines use of data')], max_length=5),
        ),
    ]
