# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0009_auto_20181116_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrequest',
            old_name='sensstatus',
            new_name='sensStatu',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='sensstatus',
            new_name='sensStatu',
        ),
        migrations.AddField(
            model_name='collection',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpreset',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontactpreset',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequest',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequestcontact',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequesthandlerchatentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequestinformationchatentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequestlogentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequestsensitivechatentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestcontact',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesthandlerchatentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestinformationchatentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlogentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestsensitivechatentry',
            name='changedBy',
            field=models.CharField(default='Field initialization', max_length=100),
            preserve_default=False,
        ),
    ]
