# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0010_auto_20181117_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrequest',
            old_name='sensStatu',
            new_name='sensStatus',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='sensStatu',
            new_name='sensStatus',
        ),
    ]
