# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 14:16
from __future__ import unicode_literals

from django.db import migrations
import pyha.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0014_auto_20181203_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='decisionExplanation',
            field=pyha.models.TruncatingCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonCorporationId',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonCountry',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonEmail',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonOrganizationName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonPhoneNumber',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonPostOfficeName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonPostalCode',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpreset',
            name='requestPersonStreetAddress',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='decisionExplanation',
            field=pyha.models.TruncatingCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonCorporationId',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonCountry',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonEmail',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonOrganizationName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonPhoneNumber',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonPostOfficeName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonPostalCode',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactpreset',
            name='requestPersonStreetAddress',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='description',
            field=pyha.models.TruncatingCharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personCorporationId',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personCountry',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personEmail',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personOrganizationName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personPhoneNumber',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personPostOfficeName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personPostalCode',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='personStreetAddress',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='reason',
            field=pyha.models.TruncatingReasonJsonCharField(blank=True, max_length=16000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='sensComment',
            field=pyha.models.TruncatingCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='sensDecisionExplanation',
            field=pyha.models.TruncatingCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personCorporationId',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personCountry',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personEmail',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personOrganizationName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personPhoneNumber',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personPostOfficeName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personPostalCode',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestcontact',
            name='personStreetAddress',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequesthandlerchatentry',
            name='message',
            field=pyha.models.TruncatingCharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='historicalrequestinformationchatentry',
            name='message',
            field=pyha.models.TruncatingCharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='historicalrequestsensitivechatentry',
            name='message',
            field=pyha.models.TruncatingCharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=pyha.models.TruncatingCharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personCorporationId',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personCountry',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personEmail',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personOrganizationName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personPhoneNumber',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personPostOfficeName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personPostalCode',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='personStreetAddress',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=pyha.models.TruncatingReasonJsonCharField(blank=True, max_length=16000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='sensComment',
            field=pyha.models.TruncatingCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='sensDecisionExplanation',
            field=pyha.models.TruncatingCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personCorporationId',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personCountry',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personEmail',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personOrganizationName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personPhoneNumber',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personPostOfficeName',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personPostalCode',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='personStreetAddress',
            field=pyha.models.TruncatingCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requesthandlerchatentry',
            name='message',
            field=pyha.models.TruncatingCharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='requestinformationchatentry',
            name='message',
            field=pyha.models.TruncatingCharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='requestsensitivechatentry',
            name='message',
            field=pyha.models.TruncatingCharField(max_length=2000),
        ),
    ]
