# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyha.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyha', '0016_auto_20181211_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserSettings',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emailNewRequests', models.CharField(choices=[('ALL', 'all requests'), ('MISSING', 'requests missing handlers'), ('NONE', 'none requests')], max_length=5)),
                ('enableCustomEmailAddress', models.BooleanField()),
                ('customEmailAddress', pyha.models.TruncatingCharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandlerInRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('emailed', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAdminUserSettings',
            fields=[
                ('user', models.CharField(db_index=True, max_length=100)),
                ('emailNewRequests', models.CharField(choices=[('ALL', 'all requests'), ('MISSING', 'requests missing handlers'), ('NONE', 'none requests')], max_length=5)),
                ('enableCustomEmailAddress', models.BooleanField()),
                ('customEmailAddress', pyha.models.TruncatingCharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical admin user settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHandlerInRequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('emailed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pyha.Request')),
            ],
            options={
                'verbose_name': 'historical handler in request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='collection',
            name='quarantineSecured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='quarantineSecured',
            field=models.IntegerField(default=0),
        ),
    ]
