# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0018_auto_20190419_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusersettings',
            name='emailNewRequests',
            field=models.CharField(choices=[('ALL', 'all requests'), ('MISSING', 'requests missing handlers'), ('NONE', 'none requests')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='adminusersettings',
            name='enableCustomEmailAddress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaladminusersettings',
            name='emailNewRequests',
            field=models.CharField(choices=[('ALL', 'all requests'), ('MISSING', 'requests missing handlers'), ('NONE', 'none requests')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaladminusersettings',
            name='enableCustomEmailAddress',
            field=models.BooleanField(default=False),
        ),
    ]
