# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyha.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyha', '0019_auto_20190419_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPyhaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingsName', pyha.models.TruncatingCharField(max_length=100)),
                ('enableDailyHandlerEmail', models.BooleanField(default=False)),
                ('enableWeeklyMissingHandlersEmail', models.BooleanField(default=False)),
                ('enableDeclineOverdueCollections', models.BooleanField(default=False)),
                ('changedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAdminPyhaSettings',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('settingsName', pyha.models.TruncatingCharField(max_length=100)),
                ('enableDailyHandlerEmail', models.BooleanField(default=False)),
                ('enableWeeklyMissingHandlersEmail', models.BooleanField(default=False)),
                ('enableDeclineOverdueCollections', models.BooleanField(default=False)),
                ('changedBy', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical admin pyha settings',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
