# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0020_adminpyhasettings_historicaladminpyhasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequestsensitivechatentry',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrequestsensitivechatentry',
            name='request',
        ),
        migrations.RemoveField(
            model_name='requestsensitivechatentry',
            name='request',
        ),
        migrations.RemoveField(
            model_name='historicalrequest',
            name='sensComment',
        ),
        migrations.RemoveField(
            model_name='historicalrequest',
            name='sensDecisionExplanation',
        ),
        migrations.RemoveField(
            model_name='historicalrequest',
            name='sensStatus',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sensComment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sensDecisionExplanation',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sensStatus',
        ),
        migrations.DeleteModel(
            name='HistoricalRequestSensitiveChatEntry',
        ),
        migrations.DeleteModel(
            name='RequestSensitiveChatEntry',
        ),
    ]
