# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 14:37
from __future__ import unicode_literals

from django.db import migrations
import pyha.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0021_auto_20191011_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='decisionExplanation',
            field=pyha.models.TruncatingCharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='decisionExplanation',
            field=pyha.models.TruncatingCharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequesthandlerchatentry',
            name='message',
            field=pyha.models.TruncatingTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='historicalrequestinformationchatentry',
            name='message',
            field=pyha.models.TruncatingTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='requesthandlerchatentry',
            name='message',
            field=pyha.models.TruncatingTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='requestinformationchatentry',
            name='message',
            field=pyha.models.TruncatingTextField(max_length=2000),
        ),
    ]
