# Generated by Django 3.0.2 on 2020-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0025_auto_20201126_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpyhasettings',
            name='enableDailyRequesterEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaladminpyhasettings',
            name='enableDailyRequesterEmail',
            field=models.BooleanField(default=False),
        ),
    ]
