# Generated by Django 3.0.2 on 2020-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0026_auto_20201202_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequest',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
