# Generated by Django 3.0.2 on 2020-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0030_auto_20201218_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequest',
            name='private_link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequest',
            name='public_link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='private_link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='public_link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
