# Generated by Django 3.0.2 on 2021-01-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0033_auto_20210119_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequest',
            name='filter_list',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='request',
            name='filter_list',
            field=models.CharField(max_length=5000),
        ),
    ]
