# Generated by Django 3.0.2 on 2021-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0034_auto_20210121_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='count_list',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='count_list',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='filter_description_list',
            field=models.CharField(max_length=16000),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='private_link',
            field=models.CharField(max_length=16000),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='public_link',
            field=models.CharField(max_length=16000),
        ),
        migrations.AlterField(
            model_name='request',
            name='filter_description_list',
            field=models.CharField(max_length=16000),
        ),
        migrations.AlterField(
            model_name='request',
            name='private_link',
            field=models.CharField(max_length=16000),
        ),
        migrations.AlterField(
            model_name='request',
            name='public_link',
            field=models.CharField(max_length=16000),
        ),
    ]
