# Generated by Django 3.0.2 on 2021-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0035_auto_20210308_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestinformationchatentry',
            name='attachedFile',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='requestinformationchatentry',
            name='attachedFile',
            field=models.BinaryField(null=True),
        ),
    ]
