# Generated by Django 3.0.2 on 2021-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0036_auto_20210913_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestinformationchatentry',
            name='attachedFileName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestinformationchatentry',
            name='attachedFileName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
