# Generated by Django 3.0.2 on 2021-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0037_auto_20210913_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='count_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='count_sum',
            field=models.IntegerField(default=0),
        ),
    ]
