# Generated by Django 3.0.2 on 2022-06-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0038_auto_20211026_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField()),
                ('fileName', models.CharField(max_length=100)),
                ('contentType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='historicalrequestinformationchatentry',
            name='file',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pyha.File'),
        ),
        migrations.AddField(
            model_name='requestinformationchatentry',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyha.File'),
        ),
    ]
