# Generated by Django 3.0.2 on 2022-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0039_auto_20220627_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequest',
            name='downloadType',
            field=models.CharField(choices=[('STANDARD', 'standard'), ('API_KEY', 'api key')], default='STANDARD', max_length=8),
        ),
        migrations.AddField(
            model_name='request',
            name='downloadType',
            field=models.CharField(choices=[('STANDARD', 'standard'), ('API_KEY', 'api key')], default='STANDARD', max_length=8),
        ),
    ]
