# Generated by Django 3.0.2 on 2022-06-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0040_auto_20220628_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequest',
            name='apiKeyExpires',
            field=models.IntegerField(choices=[(90, 'three months'), (365, 'year')], null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='apiKeyExpires',
            field=models.IntegerField(choices=[(90, 'three months'), (365, 'year')], null=True),
        ),
    ]
