# Generated by Django 3.2.15 on 2022-09-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0042_faileddownloadrequest_historicalfaileddownloadrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequestinformationchatentry',
            name='attachedFile',
        ),
        migrations.RemoveField(
            model_name='historicalrequestinformationchatentry',
            name='attachedFileName',
        ),
        migrations.RemoveField(
            model_name='requestinformationchatentry',
            name='attachedFile',
        ),
        migrations.RemoveField(
            model_name='requestinformationchatentry',
            name='attachedFileName',
        ),
    ]
