# Generated by Django 3.2.15 on 2025-08-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0043_auto_20220928_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='pyha.request'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='filter_description_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='filter_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='private_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='public_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='filter_description_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='filter_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='private_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='public_link',
            field=models.TextField(),
        ),
    ]
