# Generated by Django 3.2.15 on 2023-03-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0043_auto_20220928_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='pyha.request'),
        ),
    ]
