# Generated by Django 3.2.15 on 2025-08-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0044_alter_collection_request'),
        ('pyha', '0044_auto_20250806_1600'),
    ]

    operations = [
    ]
