version: '3'

services:
  pyha:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - 'ENABLE_DEBUG=${ENABLE_DEBUG}'
        - 'EMAIL_ERROR_RATE_LIMIT=${EMAIL_ERROR_RATE_LIMIT}'
        - 'EMAIL_ERROR_RATE_KEY_LIMIT=${EMAIL_ERROR_RATE_KEY_LIMIT}'
        - 'ADMIN_NAME=${ADMIN_NAME}'
        - 'ADMIN_EMAIL=${ADMIN_EMAIL}'
        - 'SERVER_EMAIL=${SERVER_EMAIL}'
        - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
        - 'PYHA_LISTEN_PORT=${PYHA_LISTEN_PORT}'
        - 'PYHA_URL=${PYHA_URL}'
        - 'LAJI_AUTH_URL=${LAJI_AUTH_URL}'
        - 'LAJI_ETL_FILE_DOWNLOAD_URL=${LAJI_ETL_FILE_DOWNLOAD_URL}'
        - 'TRIPLESTORE_URL=${TRIPLESTORE_URL}'
        - 'TRIPLESTORE_USER=${TRIPLESTORE_USER}'
        - 'TRIPLESTORE_PASSWORD=${TRIPLESTORE_PASSWORD}'
        - 'PDF_API_URL=${PDF_API_URL}'
        - 'PDF_API_USER=${PDF_API_USER}'
        - 'PDF_API_PASSWORD=${PDF_API_PASSWORD}'
        - 'APILAJIFI_URL=${APILAJIFI_URL}'
        - 'APILAJIFI_TOKEN=${APILAJIFI_TOKEN}'
        - 'LAJI_AUTH_TARGET=${LAJI_AUTH_TARGET}'
        - 'PYHA_API_USER=${PYHA_API_USER}'
        - 'PYHA_API_PASSWORD=${PYHA_API_PASSWORD}'
        - 'OBSERVATION_LINK_PREFIX=${OBSERVATION_LINK_PREFIX}'
        - 'OFFICIAL_OBSERVATION_LINK_PREFIX=${OFFICIAL_OBSERVATION_LINK_PREFIX}'
        - 'DB_NAME=${DB_NAME}'
        - 'DB_USER=${DB_USER}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
        - 'SKIP_OFFICIAL=${SKIP_OFFICIAL}'
        - 'DB_ENGINE=${DB_ENGINE}'
        - 'DOMAIN_PATH_PREFIX=${DOMAIN_PATH_PREFIX}'
        - 'ZABBIX_STATUS_SUB_DIR=${ZABBIX_STATUS_SUB_DIR}'
        - 'ADMIN_SUB_DIR=${ADMIN_SUB_DIR}'
        - 'STATIC_URL=${STATIC_URL}'
    env_file:
      - dev.env
    ports:
      - '8000:8000'