# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('status', models.IntegerField()),
                ('taxonSecured', models.IntegerField(default=0)),
                ('customSecured', models.IntegerField(default=0)),
                ('downloadRequestHandler', models.CharField(max_length=500, null=True)),
                ('decisionExplanation', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lajiId', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('status', models.IntegerField()),
                ('sensstatus', models.IntegerField()),
                ('sensDecisionExplanation', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=60)),
                ('user', models.CharField(max_length=100)),
                ('approximateMatches', models.IntegerField()),
                ('downloadFormat', models.CharField(max_length=40)),
                ('downloadIncludes', models.CharField(max_length=1000)),
                ('filter_list', models.CharField(max_length=2000)),
                ('reason', models.CharField(max_length=1000, null=True)),
            ],
            managers=[
                ('requests', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request'),
        ),
    ]
