# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('collection_id', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('approximateMatches', models.IntegerField()),
                ('filter_list', models.CharField(max_length=1000)),
            ],
            managers=[
                ('requests', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request'),
        ),
    ]
