# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='request',
            name='downloadFormat',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='filter_list',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='source',
            field=models.CharField(max_length=60),
        ),
    ]
