# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpreset',
            name='requestPersonCountry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='PersonCountry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestcontact',
            name='PersonCountry',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
