# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='downloadFormat',
            field=models.CharField(default='CSV_FLAT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='downloadIncludes',
            field=models.CharField(default=('DOCUMENT_FACTS',), max_length=1000),
            preserve_default=False,
        ),
    ]
