# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('W', 'watch'), ('DEL', 'delete'), ('ACC', 'accept terms of use'), ('POS', 'accept use of data'), ('NEG', 'refuse use of data')], max_length=3)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyha.Collection')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request')),
            ],
            managers=[
                ('requestLog', django.db.models.manager.Manager()),
            ],
        ),
    ]
