# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='email',
            new_name='user',
        ),
    ]
