# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogentry',
            name='action',
            field=models.CharField(choices=[('VIEW', 'views request'), ('ACC', 'accepts terms of use'), ('POS', 'accepts use of data'), ('NEG', 'declines use of data')], max_length=5),
        ),
    ]
