# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_id',
            new_name='address',
        ),
    ]
