# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0002_auto_20161021_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='customSecured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='taxonSecured',
            field=models.IntegerField(default=0),
        ),
    ]
