# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0002_auto_20170114_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInformationChatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('question', models.BooleanField()),
                ('message', models.CharField(max_length=2000)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request')),
            ],
            managers=[
                ('requestInformationChat', django.db.models.manager.Manager()),
            ],
        ),
    ]
