# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0002_auto_20161021_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='secureReasons',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
