# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0003_request_senscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestPersonCorporationId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestPersonEmail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestPersonName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestPersonOrganizationName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestPersonPhoneNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestPersonPostOfficeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestPersonPostalCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requestPersonStreetAddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
