# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0003_collection_securereasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='decisionExplanation',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
