# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0004_auto_20161223_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPreset',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('requestPersonName', models.CharField(max_length=100, null=True)),
                ('requestPersonStreetAddress', models.CharField(max_length=100, null=True)),
                ('requestPersonPostOfficeName', models.CharField(max_length=100, null=True)),
                ('requestPersonPostalCode', models.CharField(max_length=100, null=True)),
                ('requestPersonEmail', models.CharField(max_length=100, null=True)),
                ('requestPersonPhoneNumber', models.CharField(max_length=100, null=True)),
                ('requestPersonOrganizationName', models.CharField(max_length=100, null=True)),
                ('requestPersonCorporationId', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
