# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0004_collection_decisionexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sensstatus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
