# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0005_auto_20161103_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='sensstatus',
        ),
        migrations.AddField(
            model_name='request',
            name='sensstatus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
