# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0005_contactpreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestChatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request')),
            ],
            managers=[
                ('requestChat', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequestContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PersonName', models.CharField(max_length=100, null=True)),
                ('PersonStreetAddress', models.CharField(max_length=100, null=True)),
                ('PersonPostOfficeName', models.CharField(max_length=100, null=True)),
                ('PersonPostalCode', models.CharField(max_length=100, null=True)),
                ('PersonEmail', models.CharField(max_length=100, null=True)),
                ('PersonPhoneNumber', models.CharField(max_length=100, null=True)),
                ('PersonOrganizationName', models.CharField(max_length=100, null=True)),
                ('PersonCorporationId', models.CharField(max_length=100, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyha.Request')),
            ],
        ),
    ]
