# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0006_requestchatentry_requestcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonCorporationId',
            new_name='PersonCorporationId',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonEmail',
            new_name='PersonEmail',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonName',
            new_name='PersonName',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonOrganizationName',
            new_name='PersonOrganizationName',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonPhoneNumber',
            new_name='PersonPhoneNumber',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonPostOfficeName',
            new_name='PersonPostOfficeName',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonPostalCode',
            new_name='PersonPostalCode',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestPersonStreetAddress',
            new_name='PersonStreetAddress',
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
