# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0006_auto_20161103_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sensDecisionExplanation',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
