# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0003_auto_20161101_1039'),
        ('pyha', '0007_request_sensdecisionexplanation'),
    ]

    operations = [
    ]
