# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyha', '0002_auto_20161018_2210'),
        ('pyha', '0004_auto_20161017_1537'),
    ]

    operations = [
    ]
